trigger:
  branches:
    include:
      - master
      - releases/*
      - refs/tags/v*
    exclude:
      - release/*
      - standard

pr:
  branches:
    include:
      - master
      - releases/*
    exclude:
      - standard
  paths:
    exclude:
      - docs
      - doc_src
      - docs_devel
      - README.md

variables:
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]
  isRelease: $[contains(variables['Build.SourceBranch'], 'refs/tags/v')]
  isJRE8: $[contains(variables['Build.SourceBranch'], 'refs/tags/v5')]

stages:
- stage: Check
  jobs:
  - job: GitHubCI
    displayName: CI Check for master, releases/* and Pull-Requests
    pool:
      vmImage: 'ubuntu-22.04'
    condition: ne(variables['Build.Reason'], 'Schedule')
    variables:
      GRADLE_USER_HOME: '$(Pipeline.Workspace)/.gradle'
    steps:
      - template: ci/azure-pipelines/check_steps.yml

# Release build will run on the main and/or release branch, except for Pull-Request
- stage: Release
  dependsOn: Check
  condition: and(succeeded(), or(eq(variables.isMain, true), eq(variables.isRelease, true)))
  jobs:
  - job: JRE_Prep
    displayName: JRE 11 preparation for publish
    condition: ne(variables.isJRE8, true)
    pool:
      vmImage: 'ubuntu-22.04'
    steps:
      - template: ci/azure-pipelines/jre_prep.yml
  - job: JRE8_Prep
    displayName: JRE 8 preparation for publish
    condition: eq(variables.isJRE8, true)
    pool:
      vmImage: 'ubuntu-22.04'
    steps:
      - template: ci/azure-pipelines/jre8_prep.yml
  - job: ReleaseBuild
    displayName: Build for master nightly, and release
    pool:
      vmImage: 'ubuntu-22.04'
    condition: succeeded()
    variables:
      GRADLE_USER_HOME: '$(Pipeline.Workspace)/.gradle'
    steps:
      - template: ci/azure-pipelines/release_steps.yml
